### PR TITLE
Reinitialize BoardGroup's on Direct Ethernet restart.

### LINKED ISSUE #134: ghz_fpga_server fails to reconnect when direct ethernet server is restarted
We don't normally do this, but since we've been trying out the scala version of the direct ethernet server we've been restarting and noticed that after connecting to a board group once, when the direct ethernet server is restarted the ghz_fpga_server does not properly reconnect, so the devices don't appear again. Restarting both servers works, but is annoying.

### PR DESCRIPTION
**Pull request by strj**
Switches the BoardGroups to get context and connection from the
DE server every time before using either. Move the BoardGroup
Init call to aslo reinitialize existing BoardGroups on
DE server reconnecting.

Fixes #134

### CODE REVIEW

**Comment by pomalley** [comment]
If I'm reading this correctly, the idea is to no longer get a context in `BoardGroup.__init__` and hang on to it for the life of the BoardGroup, because then when the DE server restarts the context becomes bogus. However, if I recall the way contexts work (correct me if I'm wrong, Matthew), calling `server.context()` creates a new context, which we only want to do once--or rather, once we `connect()` to a DE server we need to keep that context around. So as far as I can tell this would put the wait/load/run packets in a new, different context than that which was created in `__init__` and used for `connect()`, which I don't think we want.

**Comment by strj** [comment]
Hmm, I think you're right: https://github.com/martinisgroup/pylabrad/blob/master/labrad/backend.py#L26
let me fix it up...

**Comment by maffoo** [comment]
Calling `context()` just creates a context identifier, which is a purely client-side notion. It would be ok to create this once and reuse it across restarts of the DE server, as long as you set up the _state_ associated with that context identifier each time the server restarts. But this way works as well and is arguably cleaner. LGTM after we test it on the fridge.

**Comment by strj** [comment]
Great, let me know when it's been tested and if I need to make any modifications or can push to master.

**Comment by pomalley** [comment]
@DanielSank @christopherquintana I think Jules is less busy than Vince at the moment :-) so perhaps you guys can test it there?

This also points to the fact that we need *real* tests for the FPGA server (and all the others...) but that's another issue.

**Comment by maffoo** [comment]
Tested on jules with @christopherquintana, and works great. @strj, please also bump the patch number (https://github.com/martinisgroup/servers/blob/master/GHzDACs/ghz_fpga_server.py#L180). After that, LGTM.

**Comment by JulianSKelly** [comment]
I just want to say that it's incredibly awesome getting your help @strj

**Comment by strj** [comment]
Thanks @JulianSKelly, I'm glad to help.

**Pull request merged**
