### PR TITLE
Revert timeout on COM ports to 0

### PR DESCRIPTION
**Pull request by zchen088**

### CODE REVIEW

**Comment by pomalley** [comment]
LGTM

**Comment by DanielSank** [comment]
Sure, why not? It doesn't work now anyway :-)

But seriously, does this PR mean that this actually works?

**Comment by pomalley** [comment]
It's your commit... :-)

It seems to be more solid.

**Comment by DanielSank** [comment]
"My commit"?

**Comment by pomalley** [comment]
The commit has you as the author.

**Comment by DanielSank** [comment]
> The commit has you as the author.

Indeed. See previous comment.

**Comment by zchen088** [comment]
Turns out changing the author is an annoying amount of work. Do you really care?

**Comment by zchen088** [comment]
Nevermind I think I figured it out.

**Comment by DanielSank** [comment]
For reference:


* `git config user.name "Your Name"`
* `git checkout my-branch
* `git commit -amend
* `git push -f`

**Comment by maffoo** [comment]
should also `git config user.email "you@mail.com"` to match

**Comment by DanielSank** [comment]
Yeah, that's what I said

>.>
<.<

**Comment by jwenner** [comment]
It looks like this has now been merged into master. Should the PR be marked as closed?

**Comment by DanielSank** [comment]
Yes. @zchen088, one way to make this happen automatically is to force push the branch before merging. That way github recognizes the thing you merged as the branch referred to by the PR.

**Comment by zchen088** [comment]
I thought I did, weird.

Also, you can directly change the name with ```git commit --amend --author "Name, <email>"```

**Pull request closed without merging**
