### PR TITLE
Remove builder classes and just construct channels and devs directly

### PR DESCRIPTION
**Pull request by maffoo**
The builder classes in the `org.labrad.qubits.templates` package are not needed, since we can easily construct the needed Channel, Device and Experiment classes directly.

I've also included some small naming changes here, so it's probably easiest to review by looking at the individual commits.

### CODE REVIEW

**Comment by maffoo** [comment]
Tested this successfully on vince after a couple of small fixes in scalabrad. @pomalley, do you have bandwidth to review?

**Comment by pomalley** [comment]
Yup, I'll do it tomorrow.

**Comment by pomalley** [comment]
Here's my excuse: Iris got conjunctivitis. I'll get to it ASAP, promise!

**Comment by maffoo** [comment]
Sorry to hear that, @pomalley; I hope Iris feels better. No worries :)

**Comment by pomalley** [comment]
LGTM. A couple minor scala questions but nothing to fix.

**Pull request merged**
