### PR TITLE
Add build 12 to dac.py

### PR DESCRIPTION
**Pull request by DanielSank**
Like the title says, just add build 12 to dac.py. Build 12 doesn't require any interesting changes. It's just a fix on top of build 8.

### CODE REVIEW

**Comment by pomalley** [comment]
Wait, there's a build 12? Why?

**Comment by DanielSank** [comment]
As documented in the Twiki, it adds the readback counter for SRAM executions. It *also* is supposed to fix a bug with dual block.

**Comment by maffoo** [comment]
LGTM

**Comment by DanielSank** [comment]
Manually merged but amended the commit in master so the PR didn't automatically close.

**Pull request closed without merging**
