### PR TITLE
Fix the failing ghz_fpga_test.

### LINKED ISSUE #162: ghz_fpga_server tests failing
The tests are being picked up and run as part of the data_vault server tests. A recent failure is here: https://matrix-reloaded.physics.ucsb.edu/teamcity/viewLog.html?buildId=1398&tab=buildResultsDiv&buildTypeId=Servers_DataVault

### PR DESCRIPTION
**Pull request by strj**
It seems that the test was written assuming an IDLE time offset
of -1, but in GHzDACs.Cleanup.dac.DAC_Build15 there is:
JT_IDLE_OFFSET = -0

Fixes #162.

### CODE REVIEW

**Comment by strj** [comment]
I'm not sure if the offset ought to be -1 or 0... presumably it's the test that's wrong.

**Comment by maffoo** [comment]
@pomalley, you changed this indexing recently, if I'm not mistaken. Can you take a look at @strj's fix? I'm going to take a look at creating some test jobs for the servers repo because we want to catch these test breakages early.

**Comment by pomalley** [comment]
This is the correct fix. The absolutely proper thing to do (I guess?) would be to incorporate the offsets into the test, i.e. use the class level JT_IDLE_OFFSET, etc.

**Comment by strj** [comment]
I generally lean towards not including constants from the objects being tested in the tests directly since it prevents refactorings that accidentally change the the constant and it's fairly easy to update. I'd rather add duplicate constants in the test file to make it easier to understand.

**Comment by pomalley** [comment]
I'm OK with that. LGTM (we can skip the fridge test b/c the change is only
to a test (famous last words))

**Comment by strj** [comment]
:) cool, I'll go ahead with the merge then

**Pull request merged**
