### PR TITLE
U/ben/fix agilent set v changesf

### PR DESCRIPTION
**Pull request by andrewdunsworth**

### CODE REVIEW

**Comment by andrewdunsworth** [comment]
LGTM.

**Comment by jwenner** [comment]
@andrewdunsworth, did you really merge a commit based on your LGTMing your own PR? Did someone else either take a look at or submit this PR?

**Comment by btchiaro** [comment]
I was in on this, Andrew and I worked together on this.

**Comment by jwenner** [comment]
OK, thanks.

**Pull request merged**
