### PR TITLE
Vince

### PR DESCRIPTION
**Pull request by pomalley**
what's the story with this? is it worth keeping?

@JulianSKelly , Amit...?

### CODE REVIEW

**Comment by JulianSKelly** [comment]
This is probably worth keeping, but I believe some of the changes have already been re-implemented.

**Comment by pomalley** [comment]
This is currently the active branch on Ivan (but not Vince, heh) so let's see about getting this merged in, OK? I also cherry-picked the commits from my work on the SuperMonitor because I wanted to be able to have plots where there are NaNs in the dataset, so we should merge in #44 first.

**Comment by DanielSank** [comment]
@pomalley These changes are sort of defunct now, but I think they're useful. Can you stick the dr logger stuff into the branch we made the other day where we fixed up the registry format?

**Comment by pomalley** [comment]
The DR logger commits on here were actually cherry-picked from the main branch, so there's no need to implement them again.

**Comment by DanielSank** [comment]
In that case let's just drop this branch.

**Comment by pomalley** [comment]
Agreed, except that last I looked (a couple weeks ago) it was the active one on Ivan.

**Comment by zchen088** [comment]
The Vince branch on Ivan has diverged from what's on Github, so that's pretty much it's own thing now.

**Comment by DanielSank** [comment]
Ok, then I'm closing this. We will leave the branch there until Ivan is ready to update.

**Pull request closed without merging**
