### PR TITLE
Update multi-headed data vault to work with pylabrad 0.95+

### PR DESCRIPTION
**Pull request by maffoo**
We refactor the DataVaultConnector to be a Service instead of a MultiService, and to use a single inlineCallbacks coroutine to manage the reconnection logic for a given manager. This lets us isolate the server start and stop logic which changed with pylabrad 0.95 so that we can handle both the old and new pylabrad versions.

### CODE REVIEW

**Comment by maffoo** [comment]
Test run with pylabrad 0.94.0: https://matrix-reloaded.physics.ucsb.edu/teamcity/viewLog.html?buildId=4284&tab=buildResultsDiv&buildTypeId=Servers_DataVaultMultihead

Test run with pylabrad 0.95.0: https://matrix-reloaded.physics.ucsb.edu/teamcity/viewLog.html?buildId=4285&tab=buildResultsDiv&buildTypeId=Servers_DataVaultMultihead

**Comment by maffoo** [comment]
I'd like to get this merged soon. @ejeffrey, do you think you could review?

**Comment by maffoo** [comment]
bump @ejeffrey, @DanielSank

**Comment by ejeffrey** [comment]
LGTM

**Pull request merged**
