### PR TITLE
Document Get Data Raw in the qubit sequencer

### LINKED ISSUE #262: Document return signature of qubit sequencer's .run method
Talking to Jimmy just now, I learned that only a few people in the lab understand the return signature of this incredibly important method. Surprised, I looked at the LabRAD doc and found it's almost completely blank. This is likely responsible for a feeling of mystery surrounding how to process data returned by the sequencer. In Jimmy's own words: "I had no idea about the channels, states, demod thing until ..."

Not good :P

### PR DESCRIPTION
**Pull request by DanielSank**
Fixes #262.

@maffoo I think you're the only person around here qualified to judge scala code :P

### CODE REVIEW

**Comment by DanielSank** [comment]
By the way, I used all the `|` characters because I saw that done elsewhere in the code, but it looks dorky in the python interactive shell. What's the reason for those?

**Comment by maffoo** [comment]
LGTM. The pipe characters are there to mark how much of the line is just whitespace for formatting the string literal in the source file, versus what should be in the string literal itself. A method called `unwrap` strips these out. Scalabrad calls this method, jlabrad does not. So once we finish the scalabrad conversion, these will magically disappear when looking at the docs in ipython or wherever else.

**Comment by DanielSank** [comment]
@maffoo is there a way to associate docstrings to scala methods/functions and then use them for the LabRAD string, similarly to what we do in pylabrad?

**Comment by maffoo** [comment]
@DanielSank, there's no way to reflectively access scaladoc strings at runtime, that's why you have to put the docs in annotations instead to get them to show up in labrad.

**Comment by DanielSank** [comment]
@maffoo That's too bad. Perhaps we should use a simple docstring registry with it's own decorator?

**Pull request merged**
