### PR TITLE
Remove mks_testhack references from Cryo Status HTTP server

### LINKED ISSUE #105: MKS server and web log aren't playing nice
image

### PR DESCRIPTION
**Pull request by jwenner**
http server (for web fridge status) referred to mks_gauge_server_testhack, a depreciated version of mks_gauge_server specifically for Vince (with hardcoded values). Change http server references from mks_gauge_server_testhack to mks_gauge_server.

Request reviews from Vince and Jules crews (esp. @zchen088, @DanielSank).

Fixes #105.

### CODE REVIEW

**Comment by ejeffrey** [comment]
LGTM, but I would like to hear from anyone using this that it works for
them.

**Comment by zchen088** [comment]
Yes this appears to have worked.

**Comment by maffoo** [comment]
Can we just remove the MKS gauge server testhack server entirely?

**Comment by DanielSank** [comment]
+1 for nuking

**Comment by ejeffrey** [comment]
Yes

**Pull request merged**
