### PR TITLE
Fixed the high temp (low resistance) ruox cuttoff

### PR DESCRIPTION
**Pull request by andrewdunsworth**
It uses the 4K stages temperature instead of spitting out garbage.

### CODE REVIEW

**Comment by thchwhite** [comment]
Hey I don't remember making these changes.  Am I still signed into git on the ADR computer or something?

**Comment by andrewdunsworth** [comment]
Lol, yep.  What's up with this check that failed?

**Comment by thchwhite** [comment]
Not sure I haven't used the automated error checking much.

**Comment by andrewdunsworth** [comment]
ping @maffoo

**Comment by maffoo** [comment]
Looks like there are some problems with the data vault tests on teamcity. The failures are not related to any changes in the PR, so don't let it block what you're doing here. We'll have to look into that separately.

**Comment by andrewdunsworth** [comment]
@thchwhite can you review this real quick?

**Pull request merged**
