### PR TITLE
Fix timeout recovery to work with or without executionCount

### PR DESCRIPTION
**Pull request by maffoo**
@christopherquintana

### CODE REVIEW

**Comment by DanielSank** [comment]
Setting the execution count to a string seems awkward. How about `None` instead.

**Comment by maffoo** [comment]
That's `getattr`, not `setattr`.

**Comment by DanielSank** [comment]
Touche. LGTM.

**Comment by ejeffrey** [comment]
Why not initialize execution count to None rather than have to use the getattr with a default value?

**Pull request merged**
