### PR TITLE
Convert qubit server to use scalabrad

### PR DESCRIPTION
**Pull request by maffoo**
This largely completes the migration of the qubit server to scala, including using the scalabrad api. After this, we can begin the real work of actually improving the server architecture, removing cruft, and building a new gate compiler scheme.

### CODE REVIEW

**Comment by pomalley** [comment]
Well it was a lot of Scala all at once after I hadn't looked at any for a month or more, but LGTM. Pending tests on a fridge, I suppose.

**Comment by pomalley** [comment]
Also, should move the source files under main/src/scala instead of main/src/java?

**Comment by maffoo** [comment]
Yeah, I'll add a commit to move things as a final step.

**Comment by maffoo** [comment]
Tested this with @btchiaro on the fridge; fixed one issue with channel identifiers in timing order, but otherwise everything worked fine.

**Comment by DanielSank** [comment]
YES!

**Pull request merged**
