### PR TITLE
25 lakeshore upgrade

### PR DESCRIPTION
**Pull request by andrewdunsworth**
Changed the lakeshore_370 server to read at a set speed.

### CODE REVIEW

**Comment by andrewdunsworth** [comment]
If there are no comments on this should i just merge it?

**Comment by DanielSank** [comment]
No, get a review.

**Comment by ejeffrey** [comment]
Looks good to me (LGMT).  Go ahead and merge.

**Comment by andrewdunsworth** [comment]
LGTM?

**Comment by maffoo** [comment]
Oops, I wasn't fast enough. Maybe you can address the comments in a later commit. Also, LGTM = "Looks Good To Me"

**Pull request merged**
